# Exercise on Functions:

## Task- 1:

**Create a Python program that converts between different units of measurement.**<br>
**• The program should**:<br>
**1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).**<br>
**2. Ask the user to input the value to be converted.**<br>
**3. Perform the conversion and display the result.<br>**
**4. Handle potential errors, such as invalid input or unsupported conversion types.**

In [10]:
# Task-1: Unit Converter

# Requirement 1: Function with docstring
def convert_units(conversion_type, value, direction):
    """
    Convert between length, weight, or volume.

    Parameters
    ----------
    conversion_type : str
        "length", "weight", or "volume".
    value : float
        The numeric value to be converted.
    direction : str
        For length: "m_to_ft" or "ft_to_m"
        For weight: "kg_to_lbs" or "lbs_to_kg"
        For volume: "L_to_gal" or "gal_to_L"

    Returns
    -------
    float
        Converted value.
    """
    if conversion_type == "length":
        if direction == "m_to_ft":
            return value * 3.28084               # meters -> feet
        elif direction == "ft_to_m":
            return value / 3.28084               # feet -> meters

    elif conversion_type == "weight":
        if direction == "kg_to_lbs":
            return value * 2.20462               # kg -> lbs
        elif direction == "lbs_to_kg":
            return value / 2.20462               # lbs -> kg

    elif conversion_type == "volume":
        if direction == "L_to_gal":
            return value * 0.264172              # L -> gal
        elif direction == "gal_to_L":
            return value / 0.264172              # gal -> L

    # Requirement 4: unsupported conversion type/direction
    raise ValueError("Unsupported conversion type or direction.")

# MAIN PROGRAM


try:
    # Task point 1 + Requirement 3:
    # Prompt the user to choose the type of conversion
    print("Choose the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")
    conversion_choice = input("Enter 1, 2, or 3: ")

    if conversion_choice == "1":
        conversion_type = "length"
        direction = input(
            "Enter conversion ('m_to_ft' for meters to feet, "
            "'ft_to_m' for feet to meters): "
        )

    elif conversion_choice == "2":
        conversion_type = "weight"
        direction = input(
            "Enter conversion ('kg_to_lbs' for kilograms to pounds, "
            "'lbs_to_kg' for pounds to kilograms): "
        )

    elif conversion_choice == "3":
        conversion_type = "volume"
        direction = input(
            "Enter conversion ('L_to_gal' for liters to gallons, "
            "'gal_to_L' for gallons to liters): "
        )

    else:
        # invalid menu choice
        raise ValueError("Invalid conversion type choice.")

    # Task point 2:
    # Ask the user to input the value to be converted
    value = float(input("Enter the value to be converted: "))

    # Task point 3:
    # Perform the conversion and display the result
    result = convert_units(conversion_type, value, direction)
    print(f"Converted value: {result:.4f}")

# Task point 4 + Requirement 2:
# Handle invalid input or unsupported conversion types
except ValueError as e:
    print("Error:", e)


Choose the type of conversion:
1. Length
2. Weight
3. Volume


Enter 1, 2, or 3:  1
Enter conversion ('m_to_ft' for meters to feet, 'ft_to_m' for feet to meters):  m_to_ft
Enter the value to be converted:  11


Converted value: 36.0892


## Task- 2:


**Create a Python program that performs various mathematical operations on a list of numbers.**<br>
**• The Program should:**<br>
**1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).<br>**
**2. Ask the user to input a list of numbers (separated by spaces).<br>**
**3. Perform the selected operation and display the result.**<br>
**4. Handle potential errors, such as invalid input or empty lists.**

In [2]:
# Task-2: List Operations

# Requirement 1 + 4: functions with docstrings

def calc_sum(numbers):
    """Return the sum of a list of numbers."""
    return sum(numbers)


def calc_average(numbers):
    """Return the average of a list of numbers. Raises ValueError if list is empty."""
    if not numbers:
        raise ValueError("Cannot compute average of an empty list.")
    return sum(numbers) / len(numbers)


def calc_max(numbers):
    """Return the maximum value in a list of numbers. Raises ValueError if list is empty."""
    if not numbers:
        raise ValueError("Cannot compute maximum of an empty list.")
    return max(numbers)


def calc_min(numbers):
    """Return the minimum value in a list of numbers. Raises ValueError if list is empty."""
    if not numbers:
        raise ValueError("Cannot compute minimum of an empty list.")
    return min(numbers)

# MAIN PROGRAM


try:
    # 1. Prompt the user to choose an operation
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    op_choice = input("Enter 1, 2, 3, or 4: ")

    # 2. Ask the user to input a list of numbers (separated by spaces)
    raw = input("Enter numbers separated by spaces: ")
    numbers = list(map(float, raw.split()))   # convert input to list of floats[web:62][web:68]

    if not numbers:
        raise ValueError("The list of numbers is empty.")

    # 3. Perform the selected operation and display the result
    if op_choice == "1":
        result = calc_sum(numbers)
        print("Sum:", result)
    elif op_choice == "2":
        result = calc_average(numbers)
        print("Average:", result)
    elif op_choice == "3":
        result = calc_max(numbers)
        print("Maximum:", result)
    elif op_choice == "4":
        result = calc_min(numbers)
        print("Minimum:", result)
    else:
        raise ValueError("Invalid operation choice.")

# 4. Handle potential errors (invalid input or empty list)
except ValueError as e:
    print("Error:", e)


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter 1, 2, 3, or 4:  1
Enter numbers separated by spaces:  2 2 


Sum: 4.0


## 4.2 Exercise on List Manipulation:

**1. Extract Every Other Element:<br>**
**Write a Python function that extracts every other element from a list, starting from the first element**<br>
**• Requirements:**<br>
**Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.**<br>
**Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].**

In [4]:
def extract_every_other(lst):
    """
    Return a new list containing every other element
    from lst, starting from the first element.
    """
    return lst[0::2]
    
nums = [10, 11, 12, 13, 14, 15]
print(extract_every_other(nums)) 


[10, 12, 14]


**2. Slice a Sublist:**<br>
**Write a Python function that returns a sublist from a given list, starting from a specified index and 
ending at another specified index.**<br>
**• Requirements:**<br>
**Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive) .**<br>
**Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].**



In [3]:
def get_sublist(lst, start, end):
    """
    Return a sublist from index 'start' to 'end' (inclusive).

    Parameters
    ----------
    lst : list
        Original list.
    start : int
        Starting index (inclusive).
    end : int
        Ending index (inclusive).

    Returns
    -------
    list
        Sublist from start to end (inclusive).
    """
    return lst[start:end + 1]

nums = [10, 21, 32, 43, 54, 65, 76, 87, 98, 109]
print(get_sublist(nums, 3, 7)) 


[43, 54, 65, 76, 87]


**3.Reverse a List Using Slicing:**<br>
**Write a Python function that reverses a list using slicing**<br>
**• Requirements:**<br>
**Define a function reverse_list(lst) that takes a list lst and returns a reversed list using slicing.**<br>
**Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].**

In [5]:
def reverse_list(lst):
    """
    Return a new list that is the reverse of lst,
    using slicing.
    """
    return lst[::-1]

nums = [10, 21, 32, 43, 54]
print(reverse_list(nums))


[54, 43, 32, 21, 10]


**4. Remove the First and Last Elements:**<br>
**Write a Python function that removes the first and last elements of a list and returns the resulting sublist.**<br>
**• Requirement**<br>
**Define a function remove_first_last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.**<br>
**Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].**

In [6]:
def remove_first_last(lst):
    """
    Return a new list without the first and last elements,
    using slicing.
    """
    return lst[1:-1]


# Example test with the numbers from the question
nums = [1, 2, 3, 4, 5]
print(remove_first_last(nums))   

# Another example with different numbers
nums2 = [10, 20, 30, 40, 50, 60]
print(remove_first_last(nums2))  


[2, 3, 4]
[20, 30, 40, 50]


**5. Get the First n Elements:**<br>
**Write a Python function that extracts the first n elements from a list.**<br>
**• Requirements:**<br>
**Define a function get_first_n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.**<br>
**Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].**<br>

In [8]:
def get_first_n(lst, n):
    """
    Return the first n elements of a list using slicing.

    Parameters
    ----------
    lst : list
        Original list.
    n : int
        Number of elements to take from the start.

    Returns
    -------
    list
        New list containing the first n elements.
    """
    return lst[:n]


nums = [10, 20, 30, 40, 50, 60]
print(get_first_n(nums, 3))   


[10, 20, 30]


**6. Extract Elements from the End:**<br>
**Write a Python function that extracts the last n elements of a list using slicing.**<br>
**• Requirements:–**<br>
**Define a function get_last_n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.**<br>
**Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].**

In [9]:
def get_last_n(lst, n):
    """
    Return the last n elements of a list using slicing.

    Parameters
    ----------
    lst : list
        Original list.
    n : int
        Number of elements to take from the end.

    Returns
    -------
    list
        New list containing the last n elements.
    """
    return lst[-n:]


nums = [10, 20, 30, 40, 50]
print(get_last_n(nums, 2))   


[40, 50]


**7. Extract Elements in Reverse Order:**<br>
**Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.**<br> 
**• Requirements:–**<br> 
**Define a function reverseskip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.**<br>
**Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].**

In [10]:
def reverse_skip(lst):
    """
    Return elements in reverse order, starting from the second-to-last
    element, taking every second element (skip one in between).
    """
    return lst[-2::-2]


# Example test
nums = [1, 2, 3, 4, 5, 6]
print(reverse_skip(nums))   

# Another example
nums2 = [10, 20, 30, 40, 50, 60, 70]
print(reverse_skip(nums2))  


[5, 3, 1]
[60, 40, 20]


## 4.3 Exercise on Nested List:

**1. Flatten a Nested List:**<br>
**Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.**<br>
**• Requirements:–**<br> 
**Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.**<br>
**Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].**

In [11]:
def flatten(lst):
    """
    Flatten a nested list with one level of nesting.

    Parameters
    ----------
    lst : list
        Nested list, e.g. [[1, 2], [3, 4], [5]].

    Returns
    -------
    list
        Single flat list of elements.
    """
    flat = []
    for sub in lst:
        flat.extend(sub)   # add all elements from each inner list
    return flat


# Example test
nums = [[1, 2], [3, 4], [5]]
print(flatten(nums))   


[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**<br>
**Write a Python function that extracts a specific element from a nested list given its indices.**<br>
**• Requirements:–**<br>
**Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.**<br>
**Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.**

In [12]:
def access_nested_element(lst, indices):
    """
    Return the element in a nested list at the position
    specified by a list of indices.

    Parameters
    ----------
    lst : list
        Nested list, e.g. [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
    indices : list of int
        Indices to follow into the nesting, e.g. [1, 2].

    Returns
    -------
    any
        The element found at the given nested position.
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element


# Example test 1 (given in question)
lst1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices1 = [1, 2]
print(access_nested_element(lst1, indices1))   

# Example test 2 (another example)
lst2 = [[10, 20], [30, 40, 50], [60, [70, 80], 90]]
indices2 = [2, 1, 0]
print(access_nested_element(lst2, indices2))  


6
70


**3. Sum of All Elements in a Nested List:**<br>
**Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).**<br>
**• Requirements:–**<br>
**Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.**<br>
**Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.**

In [13]:
def sum_nested(lst):
    """
    Return the sum of all numbers in a nested list, regardless of depth.

    Parameters
    ----------
    lst : list
        Nested list containing ints/floats or other lists.

    Returns
    -------
    int or float
        Sum of all numeric elements.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            # if it's a list, sum its contents recursively
            total += sum_nested(element)
        else:
            # if it's a number, add directly
            total += element
    return total


# Example test (from the question)
nums = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nums))   

# Another example
nums2 = [1, [2, 3], [[4], 5]]
print(sum_nested(nums2))  


21
15


**4. Remove Specific Element from a Nested List:**<br>
**Write a Python function that removes all occurrences of a specific element from a nested list.**<br>
**• Requirements:–**<br> 
**Define a function remove element(lst, elem) that removes elem from lst and returns themodified list.**<br>
**Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould be [[1], [3], [4, 5]]**

In [14]:
def remove_element(lst, elem):
    """
    Remove all occurrences of `elem` from a (possibly nested) list.

    Parameters
    ----------
    lst : list
        Nested list.
    elem : any
        Element to remove.

    Returns
    -------
    list
        New nested list with all occurrences of elem removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            # Clean the inner list recursively
            cleaned = remove_element(item, elem)
            result.append(cleaned)
        else:
            # Only keep items that are not equal to elem
            if item != elem:
                result.append(item)
    return result


# Example test (from the question)
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))  

# Another example
lst2 = [1, [2, 3, 2], [4, [2, 5]]]
print(remove_element(lst2, 2))    


[[1], [3], [4, 5]]
[1, [3], [4, [5]]]


**5. Find the Maximum Element in a Nested List:**<br>
**Write a Python function that finds the maximum element in a nested list (regardless of depth).**<br>
**• Requirements:–**<br> 
**Define a function find max(lst) that takes a nested list lst and returns the maximum element.**<br>
**Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.**

In [15]:
def find_max(lst):
    """
    Find the maximum numeric element in a nested list, regardless of depth.

    Parameters
    ----------
    lst : list
        Nested list containing numbers or other lists.

    Returns
    -------
    int or float
        Maximum value found in the nested structure.
    """
    current_max = None

    for element in lst:
        if isinstance(element, list):
            # Recursively find max in the sublist
            sub_max = find_max(element)
            if current_max is None or sub_max > current_max:
                current_max = sub_max
        else:
            # Element is a number
            if current_max is None or element > current_max:
                current_max = element

    return current_max


# Example test (from the question)
nums = [[1, 2], [3, [4, 5]], 6]
print(find_max(nums))   

# Another example
nums2 = [1, [10, 3], [[7, 20], 4]]
print(find_max(nums2)) 


6
20


**6. Count Occurrences of an Element in a Nested List:**<br>
**Write a Python function that counts how many times a specific element appears in a nested list.**<br>
**• Requirements:–**<br>
**Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.**<br>
**Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,the output should be 3.**

In [16]:
def count_occurrences(lst, elem):
    """
    Count how many times `elem` appears in a nested list.

    Parameters
    ----------
    lst : list
        Nested list.
    elem : any
        Element to count.

    Returns
    -------
    int
        Number of occurrences of elem in the nested structure.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recurse into inner list
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


# Example test (from the question)
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))   

# Another example
lst2 = [1, [2, 3, 2], [4, [2, 5]]]
print(count_occurrences(lst2, 2))   


3
3


**7. Flatten a List of Lists of Lists:**<br>
**Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.**<br>
**• Requirements:–**<br>
**Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.**<br>
**Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].**

In [17]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters
    ----------
    lst : list
        List that may contain other lists at any depth.

    Returns
    -------
    list
        One-dimensional list with all elements.
    """
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(deep_flatten(item))   # recurse into sublists
        else:
            flat.append(item)
    return flat


# Example test (from the question)
nums = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nums))   

# Another example
nums2 = [1, [2, [3, 4], 5], 6]
print(deep_flatten(nums2))  


[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6]


**8. Nested List Average:**<br>
**Write a Python function that calculates the average of all elements in a nested list.**<br>
**• Requirements:–**<br> 
**Define a function average_nested(lst) that takes a nested list lst and returns the average of all the elements.**<br>
**Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.**

In [18]:
def average_nested(lst):
    """
    Return the average of all numeric elements in a nested list.

    Parameters
    ----------
    lst : list
        Nested list containing numbers or other lists.

    Returns
    -------
    float
        Average of all numbers in the nested structure.
    """
    def helper(sublist):
        total = 0
        count = 0
        for item in sublist:
            if isinstance(item, list):
                sub_total, sub_count = helper(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total, count = helper(lst)
    if count == 0:
        raise ValueError("Cannot compute average of an empty nested list.")
    return total / count


# Example test (from the question)
nums = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nums))   

# Another example
nums2 = [1, [2, 3], [[4], 5]]
print(average_nested(nums2))  


3.5
3.0


# To- Do- NumPy
## Please complete all the problems listed below:

### 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem- 1: Array Creation:
#### Complete the following Tasks:

**1. Initialize an empty array with size 2X2.**

In [4]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array_2x2 = np.empty((2, 2))
print(empty_array_2x2)


[[2.17518806e+243 1.21929878e-310]
 [1.21572612e-224 5.54041855e+228]]


**2. Initialize an all one array with size 4X2.**

In [5]:
import numpy as np

# Task 2: Initialize an all-one array with size 4x2
ones_array_4x2 = np.ones((4, 2))
print(ones_array_4x2)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [6]:
import numpy as np

# Task 3: new array of given shape and type, filled with a value
filled_array = np.full((3, 2), 7, dtype=int)
print(filled_array)


[[7 7]
 [7 7]
 [7 7]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**

In [7]:
import numpy as np

# Suppose this is the given array
given_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Task 4: new array of zeros with same shape and type
zeros_same_shape = np.zeros_like(given_array)

print(given_array)
print(zeros_same_shape)


[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [8]:
import numpy as np

# Given array
given_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Task 5: new array of ones with same shape and type
ones_same_shape = np.ones_like(given_array)

print(given_array)
print(ones_same_shape)


[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [19]:
import numpy as np

new_list = [1, 2, 3, 4]

# Task 6: convert list to NumPy array
arr = np.array(new_list)

print(arr)        
print(type(arr))  


[1 2 3 4]
<class 'numpy.ndarray'>


### Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

#### Complete the following tasks:

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [10]:
import numpy as np

# Problem 2 - Task 1: array from 10 to 49
arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}**

In [11]:
import numpy as np

# values from 0 to 8
arr = np.arange(9)

# reshape to 3x3 matrix
matrix_3x3 = arr.reshape(3, 3)

print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**

In [12]:
import numpy as np

# Problem 2 - Task 3: 3x3 identity matrix
identity_3x3 = np.eye(3)
print(identity_3x3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}**

In [13]:
import numpy as np

# Problem 2 - Task 4
random_arr = np.random.random(30)   # 1D array of 30 random floats in [0, 1)
mean_value = random_arr.mean()      # compute the mean

print(random_arr)
print("Mean:", mean_value)


[0.18294773 0.50910316 0.78260234 0.47824236 0.34411239 0.6463556
 0.88454894 0.64839183 0.4127317  0.48103911 0.59402788 0.32493793
 0.48839372 0.230713   0.31704133 0.51539927 0.04562387 0.77958896
 0.43203822 0.79405034 0.67178771 0.16426261 0.87205474 0.13095953
 0.1001835  0.07339342 0.55763014 0.59760814 0.5913881  0.57220035]
Mean: 0.474111930641033


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [14]:
import numpy as np

# Problem 2 - Task 5: 10x10 random array
arr_10x10 = np.random.random((10, 10))   # random floats in [0, 1)

min_value = arr_10x10.min()
max_value = arr_10x10.max()

print(arr_10x10)
print("Minimum:", min_value)
print("Maximum:", max_value)


[[8.47980641e-01 3.04236523e-01 2.54460449e-01 3.92361133e-02
  3.82115641e-01 5.11206916e-01 9.31809803e-01 2.08345802e-01
  8.05915471e-01 5.37471818e-01]
 [2.19954896e-01 2.59450970e-01 6.89605319e-01 2.02109598e-01
  1.99698149e-01 7.27395250e-01 7.84214036e-01 7.27566993e-01
  8.47552168e-01 7.23530532e-01]
 [4.94777360e-01 8.71182616e-01 2.14995317e-01 1.84092749e-01
  9.73181946e-01 3.95490761e-03 5.65887562e-01 3.18103824e-01
  1.55779583e-01 1.60139756e-01]
 [4.15659975e-01 2.05258473e-02 8.38548454e-02 3.84578627e-01
  6.63718082e-04 5.70451885e-01 6.92364186e-01 8.66916822e-01
  2.83614389e-01 4.68878098e-01]
 [4.76634121e-01 3.12336191e-01 9.55549058e-01 2.32521247e-01
  4.00655776e-01 9.22316031e-01 8.04085103e-01 7.45322389e-01
  9.75087719e-01 3.71940224e-01]
 [2.40467431e-01 1.34425649e-02 5.92557106e-01 1.16425292e-01
  2.57853081e-02 2.91689555e-01 6.80953959e-01 2.32051777e-01
  6.26878399e-01 2.44646866e-02]
 [7.91958397e-01 9.16776004e-02 4.01941413e-01 9.06140898e

**6. Create a zero array of size 10 and replace 5th element with 1.**

In [15]:
import numpy as np

# size 10 zero array
arr = np.zeros(10)

# replace 5th element (index 4) with 1
arr[4] = 1

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [20]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr[::-1]

print(reversed_arr)   


[0 4 0 0 2 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [18]:
import numpy as np

# choose the size (for example 5x5)
n = 5
arr = np.ones((n, n), dtype=int)

# set the inner part (without border) to 0
arr[1:-1, 1:-1] = 0

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [19]:
import numpy as np

# 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# fill alternate positions with 1
checkerboard[1::2, ::2] = 1  # odd rows, even columns
checkerboard[::2, 1::2] = 1  # even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem- 3: Array Operations:

### For the following arrays:
### x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
### v = np.array([9,10]) and w = np.array([11,12]);


#### Complete all the task using numpy:

**1. Add the two array.**

In [20]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

# Problem 3 - Task 1: add the two arrays
z = x + y          # or: z = np.add(x, y)

print(z)


[[ 6  8]
 [10 13]]


**2. Subtract the two array.**

import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

# Problem 3 - Task 2: subtract the two arrays
z = x - y          # or: z = np.subtract(x, y)

print(z)


**3. Multiply the array with any integers of your choice.**

In [22]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

# Problem 3 - Task 3
x_times_3 = x * 3
y_times_2 = y * 2

print("x * 3 =\n", x_times_3)
print("y * 2 =\n", y_times_2)


x * 3 =
 [[ 3  6]
 [ 9 15]]
y * 2 =
 [[10 12]
 [14 16]]


**4. Find the square of each element of the array.**

In [24]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

x_sq = x ** 2        # or: x_sq = np.square(x)
y_sq = y ** 2        # or: y_sq = np.square(y)

print("x squared =\n", x_sq)
print("y squared =\n", y_sq)


x squared =
 [[ 1  4]
 [ 9 25]]
y squared =
 [[25 36]
 [49 64]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [27]:
import numpy as np

# Given arrays
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 5. Dot products

# (a) Dot product between v and w
dot_vw = np.dot(v, w)          # scalar

# (b) Dot product between x and v
dot_xv = np.dot(x, v)          # 2D(2x2) · 1D(2,) -> (2,)

# (c) Dot product between x and y
dot_xy = np.dot(x, y)          # 2x2 · 2x2 -> 2x2

# Print results
print("v =", v)
print("w =", w)
print("x =\n", x)
print("y =\n", y)

print("\nDot product v · w =", dot_vw)
print("Dot product x · v =", dot_xv)
print("Dot product x · y =\n", dot_xy)


v = [ 9 10]
w = [11 12]
x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]

Dot product v · w = 219
Dot product x · v = [29 77]
Dot product x · y =
 [[19 22]
 [50 58]]


**6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.**

In [28]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 6. Concatenate x and y along rows (one under the other)
xy_row = np.concatenate((x, y), axis=0)
# or equivalently:
# xy_row = np.vstack((x, y))

# 6. Concatenate v and w along columns (make a 2x2 matrix)
vw_col = np.vstack((v, w)).T
# or using concatenate explicitly:
# vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("Concatenate x and y along rows:\n", xy_row)
print("\nConcatenate v and w along columns:\n", vw_col)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [30]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

v = np.array([9, 10])

# This will cause an error:
z = np.concatenate((x, v), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Explanation:**
x has shape (2, 2) → it is 2‑dimensional.<br>
v has shape (2,) → it is 1‑dimensional.<br>
np.concatenate requires that all input arrays have the same number of dimensions along every axis except the one you concatenate on, so NumPy refuses this operation.<br>
If we want to make it work, you must first reshape v to 2D, for example as a new row:
​

In [31]:
v_row = v.reshape(1, 2)      # shape (1, 2)
z_ok = np.concatenate((x, v_row), axis=0)
print(z_ok)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


**6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.**

In [32]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 6. Concatenate x and y along row  -> stack one under the other
xy_row = np.concatenate((x, y), axis=0)
# or: xy_row = np.vstack((x, y))

# 6. Concatenate v and w along column -> make a 2x2 matrix
vw_col = np.vstack((v, w)).T
# or:
# vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("Concatenate x and y along rows:")
print(xy_row)

print("\nConcatenate v and w along columns:")
print(vw_col)


Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]]


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [33]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])   # shape (2, 2)  -> 2D array

v = np.array([9, 10])     # shape (2,)    -> 1D array

# This will raise an error:
z = np.concatenate((x, v), axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Explanation:**<br>
x is 2‑dimensional with shape (2, 2).<br>
​v is 1‑dimensional with shape (2,).<br>
​np.concatenate requires all input arrays to have the same number of dimensions, and their shapes must match on all axes except the concatenation axis.<br>
Since one array is 2D and the other is 1D, NumPy cannot align them, so it raises this error.<br>
​If we want to make it work, you must first reshape v to 2D, for example:

In [34]:
v_row = v.reshape(1, 2)           # shape (1, 2)
z_ok = np.concatenate((x, v_row), axis=0)
print(z_ok)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


### Problem- 4: Matrix Operations:
###  For the following arrays:
### A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

#### Prove following with Numpy:

**1. Prove A.A−1 = I.**

In [35]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])

# 1. Compute the inverse of A
A_inv = np.linalg.inv(A)   # uses NumPy's linear algebra module [web:326]

# 2. Multiply A and A_inv to check A · A^{-1} = I
I = A @ A_inv              # or: I = np.dot(A, A_inv)

print("A =\n", A)
print("\nA inverse =\n", A_inv)
print("\nA · A^{-1} =\n", I)


A =
 [[3 4]
 [7 8]]

A inverse =
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A · A^{-1} =
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


**2. Prove AB̸ = BA.**

In [36]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# Matrix products
AB = A @ B           # or np.dot(A, B)
BA = B @ A           # or np.dot(B, A)

print("A =\n", A)
print("B =\n", B)

print("\nA @ B =\n", AB)
print("\nB @ A =\n", BA)

print("\nAre A @ B and B @ A equal? ->", np.array_equal(AB, BA))


A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]

A @ B =
 [[23 13]
 [51 29]]

B @ A =
 [[36 44]
 [13 16]]

Are A @ B and B @ A equal? -> False


**3. Prove (AB)T = BTAT.**

In [37]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# Left-hand side: (AB)^T
AB = A @ B
lhs = AB.T                 # transpose of the product

# Right-hand side: B^T A^T
rhs = B.T @ A.T

print("A =\n", A)
print("B =\n", B)

print("\n(AB)^T =\n", lhs)
print("\nB^T A^T =\n", rhs)

print("\nAre (AB)^T and B^T A^T equal? ->", np.array_equal(lhs, rhs))


A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]

Are (AB)^T and B^T A^T equal? -> True


**Solve the following system of Linear equation using Inverse Methods.<br>
2x −3y+z =−1<br>
x −y+2z =−3<br>
3x +y−z =9<br>
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}**

In [38]:
import numpy as np

# Coefficient matrix A and constant vector B
A = np.array([[ 2, -3,  1],
              [ 1, -1,  2],
              [ 3,  1, -1]])

B = np.array([-1, -3,  9])

# Method using inverse (as in the hint)
A_inv = np.linalg.inv(A)        # compute A^{-1} [web:325]
X = A_inv @ B                   # X = A^{-1} B  [web:325]

print("Solution vector X = [x, y, z] =")
print(X)


Solution vector X = [x, y, z] =
[ 2.  1. -2.]


**Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}**

In [39]:
import numpy as np

# Coefficient matrix A
A = np.array([[ 2, -3,  1],
              [ 1, -1,  2],
              [ 3,  1, -1]])

# Constant vector B
B = np.array([-1, -3,  9])

# 1. Compute the inverse of A using numpy.linalg.inv
A_inv = np.linalg.inv(A)          # computes A^{-1} [web:326][web:327]

# 2. Solve X = A^{-1} B
X = A_inv @ B                     # matrix–vector product

print("A =\n", A)
print("\nA^{-1} =\n", A_inv)
print("\nSolution X = [x, y, z] =\n", X)


A =
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

A^{-1} =
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution X = [x, y, z] =
 [ 2.  1. -2.]


### 10.2 Experiment: How Fast is Numpy?
#### In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

#### 1. Element-wise Addition:

**Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.**

In [40]:
import time

# Create two Python lists of size 1,000,000
n = 1_000_000
list1 = list(range(n))
list2 = list(range(n))

# Measure time for element-wise addition using lists
start = time.time()

result_list = [a + b for a, b in zip(list1, list2)]

end = time.time()

print("First 5 results:", result_list[:5])
print("Time for list element-wise addition:", end - start, "seconds")


First 5 results: [0, 2, 4, 6, 8]
Time for list element-wise addition: 0.08908557891845703 seconds


**Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.**

In [41]:
import numpy as np
import time

n = 1_000_000

# Create two NumPy arrays of size 1,000,000
arr1 = np.arange(n)
arr2 = np.arange(n)

# Measure time for element-wise addition using NumPy
start = time.time()

result_np = arr1 + arr2          # vectorized addition [web:376][web:373]

end = time.time()

print("First 5 results:", result_np[:5])
print("Time for NumPy element-wise addition:", end - start, "seconds")


First 5 results: [0 2 4 6 8]
Time for NumPy element-wise addition: 0.0020055770874023438 seconds


#### 2. Element-wise Multiplication

**Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.**

In [42]:
import time

n = 1_000_000

# Two Python lists of size 1,000,000
list1 = list(range(n))
list2 = list(range(n))

# Measure time for element-wise multiplication using lists
start = time.time()

result_list = [a * b for a, b in zip(list1, list2)]  # element-wise multiply [web:380]

end = time.time()

print("First 5 results:", result_list[:5])
print("Time for list element-wise multiplication:", end - start, "seconds")


First 5 results: [0, 1, 4, 9, 16]
Time for list element-wise multiplication: 0.10484600067138672 seconds


**Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.**

In [43]:
import numpy as np
import time

n = 1_000_000

# Two NumPy arrays of size 1,000,000
arr1 = np.arange(n)
arr2 = np.arange(n)

# Measure time for element-wise multiplication using NumPy
start = time.time()

result_np = arr1 * arr2     # vectorized element-wise multiply

end = time.time()

print("First 5 results:", result_np[:5])
print("Time for NumPy element-wise multiplication:", end - start, "seconds")


First 5 results: [ 0  1  4  9 16]
Time for NumPy element-wise multiplication: 0.0025970935821533203 seconds


#### 3. Dot Product

**Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.**

In [44]:
import time

n = 1_000_000

# Two Python lists of size 1,000,000
list1 = list(range(n))
list2 = list(range(n))

# Measure time for dot product using lists
start = time.time()

dot_list = sum(a * b for a, b in zip(list1, list2))  # dot product [web:388][web:393]

end = time.time()

print("Dot product (lists) =", dot_list)
print("Time for list dot product:", end - start, "seconds")


Dot product (lists) = 333332833333500000
Time for list dot product: 0.14467620849609375 seconds


**Using Numpy Arrays, Repeat the calculation and measure and print the time taken for 
this operation**.

In [2]:
import numpy as np
import time

n = 1_000_000

# Two NumPy arrays of size 1,000,000
arr1 = np.arange(n)
arr2 = np.arange(n)

# Measure time for dot product using NumPy
start = time.time()

dot_np = np.dot(arr1, arr2)      # or: arr1 @ arr2

end = time.time()

print("Dot product (NumPy) =", dot_np)
print("Time for NumPy dot product:", end - start, "seconds")


Dot product (NumPy) = 584144992
Time for NumPy dot product: 0.00032639503479003906 seconds


#### 4. Matrix Multiplication

**Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.**

In [1]:
import time

size = 1000

# Two 1000x1000 matrices as Python lists
A = [[1] * size for _ in range(size)]
B = [[1] * size for _ in range(size)]

start = time.time()

# Matrix multiplication using pure Python lists
result = [
    [sum(A[i][k] * B[k][j] for k in range(size))
     for j in range(size)]
    for i in range(size)
]

end = time.time()

print("Python matrix multiplication time:", end - start, "seconds")


Python matrix multiplication time: 93.4186782836914 seconds


**Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.**

In [1]:
import numpy as np
import time

n = 1000

# Two 1000x1000 matrices as NumPy arrays
A = np.random.rand(n, n)
B = np.random.rand(n, n)

start = time.time()

# Matrix multiplication C = A * B using NumPy
C = A @ B            # or: C = np.matmul(A, B) or np.dot(A, B)

end = time.time()

print("C[0, 0] =", C[0, 0])
print("Time for 1000x1000 matrix multiply using NumPy:", end - start, "seconds")


C[0, 0] = 253.5875184972187
Time for 1000x1000 matrix multiply using NumPy: 0.08356952667236328 seconds
